import { chmodSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { platform as osPlatform } from "node:os";

export type ImportScriptPaths = {
  /** POSIX shell script (Linux / macOS). */
  sh: string;
  /** Windows batch script. */
  bat: string;
};

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function batEscape(value: string): string {
  // Percent signs and carets are special in cmd; quotes handle spaces.
  return value.replace(/%/g, "%%").replace(/"/g, '""');
}

/**
 * Write companion scripts next to downloaded .osz archives so the user can
 * import them into osu!lazer later:
 * - `import-into-osu.sh` — prefers `osu!` / `osu` on PATH, else `xdg-open` / `open`
 * - `import-into-osu.bat` — `start "" file.osz` (Windows file association)
 */
export function writeOsuImportScripts(
  downloadDir: string,
  oszPaths: string[],
): ImportScriptPaths {
  const shPath = path.join(downloadDir, "import-into-osu.sh");
  const batPath = path.join(downloadDir, "import-into-osu.bat");

  const relativeOrAbs = (filePath: string): string => {
    const rel = path.relative(downloadDir, filePath);
    if (!rel.startsWith("..") && !path.isAbsolute(rel)) return rel;
    return filePath;
  };

  const shLines = [
    "#!/usr/bin/env bash",
    "# Generated by Roxysu — open downloaded .osz archives in osu!lazer.",
    "set -euo pipefail",
    'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    "cd \"$DIR\"",
    "",
    "open_one() {",
    "  local f=$1",
    '  if command -v "osu!" >/dev/null 2>&1; then',
    '    "osu!" "$f" >/dev/null 2>&1 &',
    "  elif command -v osu >/dev/null 2>&1; then",
    '    osu "$f" >/dev/null 2>&1 &',
    "  elif command -v osu-lazer >/dev/null 2>&1; then",
    '    osu-lazer "$f" >/dev/null 2>&1 &',
    "  elif [[ \"$(uname -s)\" == Darwin ]]; then",
    '    open "$f"',
    "  else",
    '    xdg-open "$f" >/dev/null 2>&1 || open "$f"',
    "  fi",
    "  sleep 0.5",
    "}",
    "",
    `echo "Importing ${oszPaths.length} beatmap archive(s) into osu!…"`,
  ];

  for (const filePath of oszPaths) {
    const rel = relativeOrAbs(filePath).replace(/\\/g, "/");
    shLines.push(`open_one ${shellSingleQuote(rel)}`);
  }
  shLines.push('echo "Done. Check osu!lazer for import prompts."');
  shLines.push("");

  writeFileSync(shPath, shLines.join("\n"), { encoding: "utf8" });
  try {
    chmodSync(shPath, 0o755);
  } catch {
    // Non-POSIX filesystems may reject chmod; script is still usable via `bash`.
  }

  const batLines = [
    "@echo off",
    "REM Generated by Roxysu — open downloaded .osz archives in osu!lazer.",
    "setlocal EnableExtensions",
    'set "DIR=%~dp0"',
    'cd /d "%DIR%"',
    `echo Importing ${oszPaths.length} beatmap archive(s) into osu!...`,
  ];

  for (const filePath of oszPaths) {
    const rel = relativeOrAbs(filePath);
    const escaped = batEscape(rel);
    batLines.push(`start "" "${escaped}"`);
    batLines.push("timeout /t 1 /nobreak >nul");
  }
  batLines.push("echo Done. Check osu!lazer for import prompts.");
  batLines.push("endlocal");
  batLines.push("");

  writeFileSync(batPath, batLines.join("\r\n"), { encoding: "utf8" });

  return { sh: shPath, bat: batPath };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function spawnDetached(command: string, args: string[]): void {
  const child = spawn(command, args, {
    detached: true,
    stdio: "ignore",
    windowsHide: true,
  });
  child.unref();
}

/**
 * Open one .osz with the OS default / osu! handler.
 * Linux: `osu!` / `osu` / `osu-lazer` if on PATH, else `xdg-open`.
 * macOS: `open`.
 * Windows: `cmd /c start "" path`.
 */
export async function openOszWithOsu(
  filePath: string,
  platform: NodeJS.Platform = osPlatform() as NodeJS.Platform,
): Promise<void> {
  if (platform === "win32") {
    spawnDetached("cmd", ["/c", "start", "", filePath]);
    return;
  }
  if (platform === "darwin") {
    spawnDetached("open", [filePath]);
    return;
  }

  // Linux and other POSIX: try lazer binaries, then xdg-open.
  const candidates = ["osu!", "osu", "osu-lazer"];
  for (const bin of candidates) {
    try {
      await new Promise<void>((resolve, reject) => {
        const child = spawn(bin, [filePath], {
          detached: true,
          stdio: "ignore",
        });
        child.on("error", reject);
        child.unref();
        // If spawn succeeds without immediate error, assume it worked.
        setTimeout(() => resolve(), 50);
      });
      return;
    } catch {
      // try next
    }
  }
  spawnDetached("xdg-open", [filePath]);
}

export type OpenOszBatchResult = {
  opened: number;
  failed: number;
  openedPaths: string[];
  errors: Array<{ path: string; error: string }>;
  platform: string;
};

/** Open many archives with a short delay so lazer is not flooded. */
export async function openOszFilesInOsu(
  filePaths: string[],
  opts?: {
    delayMs?: number;
    shouldStop?: () => boolean;
    platform?: NodeJS.Platform;
  },
): Promise<OpenOszBatchResult> {
  const delayMs = opts?.delayMs ?? 600;
  const platform = opts?.platform ?? (osPlatform() as NodeJS.Platform);
  let opened = 0;
  let failed = 0;
  const openedPaths: string[] = [];
  const errors: Array<{ path: string; error: string }> = [];

  for (const filePath of filePaths) {
    if (opts?.shouldStop?.()) break;
    try {
      await openOszWithOsu(filePath, platform);
      opened += 1;
      openedPaths.push(filePath);
    } catch (err) {
      failed += 1;
      errors.push({
        path: filePath,
        error: err instanceof Error ? err.message : String(err),
      });
    }
    if (delayMs > 0) await sleep(delayMs);
  }

  return {
    opened,
    failed,
    openedPaths,
    errors: errors.slice(0, 8),
    platform,
  };
}
